In [1]:
import numpy as np

array_1 = np.array([1,2,3,4,5])


In [5]:
array_1.reshape(1, 5)

array([[1, 2, 3, 4, 5]])

In [6]:
array_2 = np.array([[1,2,3,4,5], [2,3,4,6,7]])

In [8]:
print(array_2.shape)

(2, 5)


In [9]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
array_3 = np.array([[1,2,3], [4,5,6]])

In [12]:
print(array_3)
print(array_3.shape)
print(array_3.ndim)
print(array_3.size)


[[1 2 3]
 [4 5 6]]
(2, 3)
2
6


In [17]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

In [21]:
print(arr1 / arr2)

[0.1 0.1 0.1 0.1 0.1]


In [25]:
array_1 = np.array([2,3,4,5,6])

print(np.sqrt(array_1))
print(np.exp(array_1))
print(np.sin(array_1))
print(np.log(array_1))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [26]:
array_4 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [28]:
print(array_4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
array_4[2][2]

np.int64(11)

In [27]:
print(array_4[1:, 1:3])

[[ 6  7]
 [10 11]]


In [31]:
array_4[2][2] = 100

In [32]:
array_4

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10, 100,  12]])

In [35]:
normalized_arr = (array_4 - np.mean(array_4)) / np.std(array_4)

In [37]:
print(normalized_arr)

[[-0.49397388 -0.45573074 -0.4174876  -0.37924447]
 [-0.34100133 -0.30275819 -0.26451505 -0.22627191]
 [-0.18802877 -0.14978563  3.29209691 -0.07329935]]


In [39]:
import pandas as pd

In [43]:
data = [1,2,3,4,5]

series = pd.Series(data)

print(type(series))

<class 'pandas.core.series.Series'>


In [44]:
data = {'a': 1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64


In [45]:
data = [10,20,30]
index = ['a', 'b', 'c']

pd.Series(data, index=index)

a    10
b    20
c    30
dtype: int64

In [46]:
data = {
    'Name': ['Hasnain', 'Ali', 'Raza'],
    'Age': [28, 27, 29],
    'City': ['Karachi', "Lahore", 'Islamabad']
}

In [48]:
df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age       City
0  Hasnain   28    Karachi
1      Ali   27     Lahore
2     Raza   29  Islamabad
<class 'pandas.core.frame.DataFrame'>


In [49]:
df = pd.read_csv('archive/sales_data_sample.csv')

In [50]:
df.head(5)

ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0        10107               30      95.70                2  2871.00   
1        10121               34      81.35                5  2765.90   
2        10134               41      94.74                2  3884.34   
3        10145               45      83.26                6  3746.70   
4        10159               49     100.00               14  5205.27   

         ORDERDATE   STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
0   2/24/2003 0:00  Shipped       1         2     2003  ...   
1    5/7/2003 0:00  Shipped       2         5     2003  ...   
2    7/1/2003 0:00  Shipped       3         7     2003  ...   
3   8/25/2003 0:00  Shipped       3         8     2003  ...   
4  10/10/2003 0:00  Shipped       4        10     2003  ...   

                    ADDRESSLINE1  ADDRESSLINE2           CITY STATE  \
0        897 Long Airport Avenue           NaN            NYC    NY   
1             59 rue de l'Abbaye           NaN          Reims   NaN   
2  27 rue du Colonel Pierre Avia           NaN          Paris   NaN   
3             78934 Hillside Dr.           NaN       Pasadena    CA   
4                7734 Strong St.           NaN  San Francisco    CA   

  POSTALCODE COUNTRY TERRITORY CONTACTLASTNAME CONTACTFIRSTNAME DEALSIZE  
0      10022     USA       NaN              Yu             Kwai    Small  
1      51100  France      EMEA         Henriot             Paul    Small  
2      75508  France      EMEA        Da Cunha           Daniel   Medium  
3      90003     USA       NaN           Young            Julie   Medium  
4        NaN     USA       NaN           Brown            Julie   Medium  

[5 rows x 25 columns]

In [51]:
df.tail(5)

ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
2818        10350               20     100.00               15  2244.40   
2819        10373               29     100.00                1  3978.51   
2820        10386               43     100.00                4  5417.57   
2821        10397               34      62.24                1  2116.16   
2822        10414               47      65.52                9  3079.44   

           ORDERDATE    STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
2818  12/2/2004 0:00   Shipped       4        12     2004  ...   
2819  1/31/2005 0:00   Shipped       1         1     2005  ...   
2820   3/1/2005 0:00  Resolved       1         3     2005  ...   
2821  3/28/2005 0:00   Shipped       1         3     2005  ...   
2822   5/6/2005 0:00   On Hold       2         5     2005  ...   

               ADDRESSLINE1  ADDRESSLINE2      CITY STATE POSTALCODE  COUNTRY  \
2818     C/ Moralzarzal, 86           NaN    Madrid   NaN      28034    Spain   
2819            Torikatu 38           NaN      Oulu   NaN      90110  Finland   
2820     C/ Moralzarzal, 86           NaN    Madrid   NaN      28034    Spain   
2821  1 rue Alsace-Lorraine           NaN  Toulouse   NaN      31000   France   
2822     8616 Spinnaker Dr.           NaN    Boston    MA      51003      USA   

     TERRITORY CONTACTLASTNAME CONTACTFIRSTNAME DEALSIZE  
2818      EMEA          Freyre            Diego    Small  
2819      EMEA       Koskitalo           Pirkko   Medium  
2820      EMEA          Freyre            Diego   Medium  
2821      EMEA          Roulet          Annette    Small  
2822       NaN         Yoshido             Juri   Medium  

[5 rows x 25 columns]

In [53]:
df['ORDERNUMBER']

0       10107
1       10121
2       10134
3       10145
4       10159
        ...  
2818    10350
2819    10373
2820    10386
2821    10397
2822    10414
Name: ORDERNUMBER, Length: 2823, dtype: int64

In [54]:
df.loc[0]

ORDERNUMBER                           10107
QUANTITYORDERED                          30
PRICEEACH                              95.7
ORDERLINENUMBER                           2
SALES                                2871.0
ORDERDATE                    2/24/2003 0:00
STATUS                              Shipped
QTR_ID                                    1
MONTH_ID                                  2
YEAR_ID                                2003
PRODUCTLINE                     Motorcycles
MSRP                                     95
PRODUCTCODE                        S10_1678
CUSTOMERNAME              Land of Toys Inc.
PHONE                            2125557818
ADDRESSLINE1        897 Long Airport Avenue
ADDRESSLINE2                            NaN
CITY                                    NYC
STATE                                    NY
POSTALCODE                            10022
COUNTRY                                 USA
TERRITORY                               NaN
CONTACTLASTNAME                 